default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://booklog:password@localhost:5433/booklog_dev") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://booklog:password@localhost:5433/booklog_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
